#!/usr/bin/env bash
#Configures an Nginx server to listen on port 80
#configures nginx to listen on port 80 for all active Ips
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
